### ISSUE TITLE
Issue running in Heroku (and elsewhere)

### ISSUE THREAD

**Issue by flyize** [davidkassa/southwest-checkin-3#1]
I'm trying to run your updated version and I'm getting this error when deploying to Heroku.

```
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateAirports < ActiveRecord::Migration[4.2]

```

**Comment by davidkassa** [comment]
Hmmm, I'll take a look. I already had an existing Heroku instance before upgrading. There's a chance I'm still pointing to an old environment or didn't upgrade the migration path.

**Comment by davidkassa** [comment]
fixed in last checkin
