### ISSUE TITLE
Add reservation error

### ISSUE THREAD

**Issue by mkitchingh** [davidkassa/southwest-checkin-3#24]
I'm a long time user of the previous versions of this app. My last working instance was a local Ubuntu instance of version 2. It is getting an error now adding a reservation. I decided to try your version in a new Heroku instance. I tried adding 2 separate flights, and they both error out. 
Any ideas?
There was a problem retrieving your reservation. Please check the following fields to make sure they are correct:
Payload can't be blank
User reservations is invalid

**Comment by davidkassa** [comment]
I heard that sw is blocking Heroku IPs. I have but yet added a proxy but that could solve it.

**Comment by mkitchingh** [comment]
That is why I originally switched off Heroku. Is this working anywhere for you? My version 2 on Ubuntu is getting an error as well:
There was a problem retrieving your reservation. Please check the following fields to make sure they are correct:

**Comment by davidkassa** [comment]
No reservations to test it right now but all the tests work. That's why it felt like a Heroku issue.

**Comment by mkitchingh** [comment]
So are you running a locally? On Ubuntu? Any tips for a current local
install? Is there a specific version of Ubuntu still required?

**Comment by mkitchingh** [comment]
Tried the Heroku site today, and it worked. I let it go to sleep overnight. I wonder if it came back up at a different IP. I had 5 flights to add, and they all worked. Is the proxy setup something you plan to code, or a Heroku plugin?

**Comment by davidkassa** [comment]
A plug-in that requires a little bit of code (maybe none?) I was looking at fixie and some others.

**Comment by mkitchingh** [comment]
I'll give Fixie free a try and see what happens.

**Comment by mkitchingh** [comment]
Fixie seemed to break the app. I got the same error I was getting yesterday, and Fixie showed it handled 0 requests. I removed it, and Checkin worked again.

**Comment by mkitchingh** [comment]
I'm thinking it would require some code changes to use Fixie (see about 1/3 of the way down):
https://devcenter.heroku.com/articles/fixie

**Comment by mkitchingh** [comment]
Sorry for all the posts. The free version of Fixie may not work too well. It has a limit of 500 requests a month. I assume you use something like Uptime Robot to keep your site online? Or has someone found a way to wake it up when it needs to fire off a task. If using the Uptime Robot approach, I believe every response to UR would count as a request.

**Comment by davidkassa** [comment]
No uptime robot as the free Heroku tier is now a flat number of hours. If I have a trip late in the month I'll upgrade my plan for < $5

**Comment by mkitchingh** [comment]
But they Dyno still goes to sleep if something isn't hitting to keep it awake. Does your version of the app wake it up when an event needs to fire off?

**Comment by davidkassa** [comment]
Stays awake as a job. Iirc

**Comment by mkitchingh** [comment]
I'm not following you. I paused uptime Robot and my Dyno went to sleep 30 minutes later. In version 2, nothing would wake it up. Are you saying something should be keeping it awake all the time, or a job will somehow wake it up when it needs to do a check-in task.

**Comment by mkitchingh** [comment]
I had a checkin today, but it failed because my Heroku IP appears to be blocked. I have another checkin Tuesday evening if there is anything for me to try. I can also do a local instance. Do you know what version of Ubuntu it is supposed to use currently? I know the version 2 was very specific on this. If using Fixie/Heroku I'd like to keep it free. I can keep it under 500 with Uptime robot. If there is an internal method to wake it up when a job needs to fire, that would really be ideal. If there is an internal job to keep it alive all the time, that would work fine too.

**Comment by mkitchingh** [comment]
I'm sure you are tired of hearing from me. I've tried all morning to figure out where to put the Fixie code. I am not having any luck so far. It fails to compile wherever I try it.

**Comment by davidkassa** [comment]
Not tired at all...this is exactly what community is about. There could be a chance that they're blocking Fixie too. I'll take a look and see if I can help. The flyize fork does have some recently updated Ubuntu instructions available too.

**Comment by mkitchingh** [comment]
They aren't blocking Fixie, I just can't get it to use Fixie. I think I get a new IP when I restart my Dynos. The current was is working for check-ins, but I can't get it to use Fixie.

**Comment by davidkassa** [comment]
As a final note regarding uptime robot - you don't need it but you do need to manually enable the worker dyno.
![image](https://user-images.githubusercontent.com/814849/63317083-15bd5e80-c2d7-11e9-9567-53ebf825d059.png)

**Comment by davidkassa** [comment]
it will make you run out of the 1000 free hours per month, though. so toggle as you see fit.

**Comment by mkitchingh** [comment]
That makes sense. I think I will leave it toggled off and have uptime robot keep it up during appropriate hours. You are saying since it has 2 dynos, it uses 2 free hours for every hour that it is awake?
