### ISSUE TITLE
Migrate from v2 to v3?

### ISSUE THREAD

**Issue by flyize** [davidkassa/southwest-checkin-3#54]
I have a server running the old v2 code.  Is there an easy way to migrate to this version, while keeping all user logins and reservations from the old system?

Thanks for all the work.  Glad to see someone who knows what they're doing back working on this!

**Comment by mkitchingh** [comment]
Maybe update your github repository and then push to heroku? I can't remember if I lost data. I don't think I did.

**Comment by flyize** [comment]
Duh!  It's been a long day.

I guess I should try that before actually bothering anyone.  Although I'm not using Heroku.

**Comment by davidkassa** [comment]
should be 100% compatible with v2. Data shouldn't be lost - if you're self-hosting it's worth backing up first :)
