### ISSUE TITLE
Use Proxy and Proxy settings

### ISSUE THREAD

**Issue by davidkassa** [davidkassa/southwest-checkin-3#6]

**Comment by mkitchingh** [comment]
I hope you can figure this out. I have tried putting the Fixie code in about 15 different places, and none of them will work for me.

**Comment by davidkassa** [comment]
can you check out my fixie branch? Hopefully it's what's needed.

**Comment by mkitchingh** [comment]
You nailed it! Awesome! Normal traffic is not going through Fixie, but outbound traffic generated by the app is. Nice work. I was close, but definitely had errors in my attempt. See pic of successful traffic. 
<img width="883" alt="Fixie" src="https://user-images.githubusercontent.com/25916510/63315771-11db0d80-c2d2-11e9-8ca2-6e646102e30d.PNG">

**Comment by mkitchingh** [comment]
I added a reservation successfully, and I have checkin that should fire tomorrow night.
